@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(customer, "Bank customer", "Uses banking services")
Person(ccm, "Call center manager", "Handles customer requests created on the website")
Person(bom, "Back office manager", "Confirms customer requests")
System(app, "Bank System", "Processes customer requests, manages banking operations")
System_Ext(ccSystem, "Call center System", $descr="System for managing user requests")

Rel(ccm, ccSystem, "Uses")
Rel_U(customer, app, "Uses")
Rel(bom, app, "Uses")
Rel_R(app, ccSystem, "Sends customer requests for processing")
@enduml
